--créer utilisateur caissier/test (Tiavina)
--menu
--caisse
--vente
--achat
 
INSERT INTO UTILISATEUR
(REFUSER, LOGINUSER, PWDUSER, NOMUSER, ADRUSER, TELUSER, IDROLE)
VALUES(1528, 'caissier', 'paop', 'caissier', 'DIR42', '1002067', 'dg');
 
INSERT INTO PARAMCRYPT
(ID, NIVEAU, CROISSANTE, IDUTILISATEUR)
VALUES('5', 4, 1, '1528');
 
INSERT INTO CNAPS_USER
(ID, CODE_DR, USER_INIT, AGENT_MO, AGENT_DISPONIBLE, USERNAME, CODE_SERVICE, ID_UTILISATEUR)
VALUES('CNP15', 'DIR00001', '1', '1', '1', 'caissier', '2030', '1528');
 
 
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0528', 1528, 'MENUDYN001', NULL, NULL, NULL, NULL);
 
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0529', 1528, 'MNDN000000001', NULL, NULL, NULL, NULL);
 
INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0530', 1528, 'MNDN000000002', NULL, NULL, NULL, NULL);