INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT377', 'PERFECT MADAGASCAR', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT378', 'ABS', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT379', 'MED', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT380', 'ECC', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT381', 'ESP BIG', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT382', 'DELTA', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT383', 'SOMADIS', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT384', 'SHINE', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT385', 'MADO', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT386', 'BIO BELLA', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT387', 'FORA TRANO', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT388', 'ES DES', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT389', 'CFP CREAFOR', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT390', 'ISSSD TSARASAOTRA', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT391', 'EKAR AMBOHIMENNA', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT392', 'DREAM CONSULTING', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT393', 'ADES', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT394', 'CHEZ TATA', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT395', 'MANABE', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT396', 'TAS MADAGASCAR', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT397', 'ALL BABA MOHAN', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT398', 'PASTEUR NARY', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT399', 'JEAN CEDIL', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT400', 'EVARISTE', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT401', 'FITSABOANA NATORALY', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT402', 'UNIVERS MADA', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT403', 'ONIFRA ANTSIRABE', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT404', 'PRETRE VIJAY', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT405', 'FLM MIARIKOFEHY', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT406', 'MPIASA PORT', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT407', 'KONFERANSA ADVENTISTE', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT408', 'MPITSABO FIDERANA', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT409', 'IFSTP', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT410', 'ISMATEC', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT411', 'ILC MAHAJANGA', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT412', 'GAZA BOY', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT413', 'MALALANIAINA', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT414', 'RATAH', null, null, null, null, '401001', null, 'Commerical', null, null);
INSERT INTO CLIENT (ID, NOM, TELEPHONE, MAIL, ADRESSE, REMARQUE, COMPTE, IDNATIONALITE, TYPE, NIF, STAT) VALUES ('CLIENT415', 'ILOAINA', null, null, null, null, '401001', null, 'Commerical', null, null);















DELETE FROM BONDECOMMANDE_CLIENT_FILLE;
DELETE FROM BONDECOMMANDE_CLIENT;

DELETE FROM VENTE_DETAILS;
DELETE FROM VENTE;


DELETE FROM RESERVATIONDETAILS;
DELETE FROM RESERVATION;

DELETE FROM PARRAINAGEEMISSIONDETAILS;
DELETE FROM PARRAINAGEEMISSION;

ALTER TABLE CLIENT ADD
    DATY DATE;
