ALTER TABLE CATEGORIEINGREDIENT
    ADD CODECOULEUR VARCHAR2(255);
ALTER TABLE EMISSION
    ADD COUPURE INTEGER;
ALTER TABLE EMISSIONDETAILS
    ADD COUPURE INTEGER;


create or replace view EMISSION_LIB AS
SELECT
    e.*,
    te.VAL as idGenreLib,
    s.VAL as idSupportLib
FROM EMISSION e
         LEFT JOIN TYPEEMISSION te ON te.ID = e.IDGENRE
         LEFT JOIN SUPPORT s ON s.ID = e.IDSUPPORT;

CREATE OR REPLACE VIEW EMISSIONDETAILS_LIB AS
SELECT
    emd.*,
    e.NOM as libelleemission,
    e.IDSUPPORT,
    e.IDGENRE,
    e.idSupportLib,
    e.idGenreLib
FROM EMISSIONDETAILS emd
         LEFT JOIN EMISSION_LIB e ON e.ID = emd.IDMERE;

insert into AS_INGREDIENTS (ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV, LIBELLEVENTE, SEUILMIN, SEUILMAX, PUACHATUSD, PUACHATEURO, PUACHATAUTREDEVISE, PUVENTEUSD, PUVENTEEURO, PUVENTEAUTREDEVISE, ISVENTE, ISACHAT, COMPTE_VENTE, COMPTE_ACHAT, LIBELLEEXTACTE, TVA, PU1, PU2, PU3, PU4, PU5, IDSUPPORT, DUREE,DUREEMAX)
values ('INGDKLT00081', 'Plateau', 100.00, 'UNT003', 1.00, 200000.00, 0, null, 0.00, null, 0, 'CATING000043', null, DATE '2025-06-16', 0.00, 200000.00, null, null, null, null, null, null, null, null, null, 1, 0, '710010', '610010', 'Service plateau', 20.00, 200000.00, 200000.00, 200000.00, 200000.00, 200000.00, 'SUPP002', 1,2);
