CREATE OR REPLACE VIEW INSERTION_PROFORMA_DETAILS AS
SELECT p.*,
       '' AS uniteRemise
FROM PROFORMA_DETAILS p;

CREATE OR REPLACE VIEW InsertionBcFille AS
SELECT p.*,
       '' AS uniteRemise
FROM BONDECOMMANDE_CLIENT_FILLE p;
