ALTER TABLE AVOIRFCFILLE ADD COMPTE VARCHAR2(255);

CREATE OR REPLACE
VIEW VENTE_DETAILS_VISEE AS
SELECT
	vd.*
FROM
	VENTE_DETAILS vd
JOIN VENTE v ON
	vd.IDVENTE = v.id
WHERE
	v.ETAT >= 11;

CREATE OR REPLACE
VIEW "KOLOTV"."AVOIRFCFILLELIB" ("ID",
"IDAVOIRFC",
"IDPRODUIT",
"IDORIGINE",
"QTE",
"PU",
"REMISE",
"TVA",
"PUACHAT",
"PUVENTE",
"IDDEVISE",
"TAUXDECHANGE",
"DESIGNATION",
"IDVENTEDETAILS",
"IDPRODUITLIB",
"COMPTE") AS
SELECT
	AF.ID,
	AF.IDAVOIRFC,
	AF.IDPRODUIT,
	AF.IDORIGINE,
	AF.QTE,
	AF.PU,
	AF.REMISE,
	AF.TVA,
	AF.PUACHAT,
	AF.PUVENTE,
	AF.IDDEVISE,
	AF.TAUXDECHANGE,
	AF.DESIGNATION,
	AF.IDVENTEDETAILS,
	P.LIBELLE AS IDPRODUITLIB,
	AF.COMPTE 
FROM
	AVOIRFCFILLE AF
LEFT JOIN AS_INGREDIENTS P ON
	P.id = AF.IDPRODUIT;