UPDATE MENUDYNAMIQUE
SET LIBELLE='Saisie', ICONE='fa fa-plus', HREF='module.jsp?but=acte/acte-saisie.jsp', RANG=2, NIVEAU=2, ID_PERE='EN'
WHERE ID='ELM001104002';

UPDATE MENUDYNAMIQUE
SET LIBELLE='&Eacute;mission', ICONE='fa fa-camera-retro', HREF=NULL, RANG=1, NIVEAU=2, ID_PERE='ELM0011040010'
WHERE ID='ELM0011040011';

UPDATE MENUDYNAMIQUE
SET LIBELLE='&Eacute;mission', ICONE='fa fa-tv', HREF=NULL, RANG=6, NIVEAU=1, ID_PERE=NULL
WHERE ID='ELM0011040010';

UPDATE MENUDYNAMIQUE
SET LIBELLE='Service', ICONE='fa fa-tags', HREF=NULL, RANG=8, NIVEAU=1, ID_PERE=NULL
WHERE ID='MNDN00001';

UPDATE MENUDYNAMIQUE
SET LIBELLE='Creation', ICONE='fa fa-plus', HREF='module.jsp?but=produits/as-ingredients-saisie.jsp', RANG=1, NIVEAU=2, ID_PERE='EN'
WHERE ID='MNDN000011';

UPDATE MENUDYNAMIQUE
SET LIBELLE='Création produit', ICONE='fa fa-plus', HREF='module.jsp?but=produits/produits-saisie.jsp', RANG=2, NIVEAU=2, ID_PERE='EN'
WHERE ID='MNDN000013';

UPDATE MENUDYNAMIQUE
SET LIBELLE='Produits achats', ICONE='fa fa-list', HREF='module.jsp?but=annexe/produit/produit-achat-liste.jsp', RANG=5, NIVEAU=2, ID_PERE='EN'
WHERE ID='MNDN0180414001';

UPDATE MENUDYNAMIQUE
SET LIBELLE='M&eacute;dia', ICONE='fa fa-play-circle', HREF=NULL, RANG=2, NIVEAU=2, ID_PERE='MNDT1505001340011'
WHERE ID='MNDT1505001340015';

UPDATE MENUDYNAMIQUE
SET LIBELLE='M&eacute;dia', ICONE='fa fa-video-camera', HREF=NULL, RANG=10, NIVEAU=1, ID_PERE=NULL
WHERE ID='MNDT1505001340011';

UPDATE MENUDYNAMIQUE
SET LIBELLE='Pr&eacute;vision', ICONE='fa fa-tags', HREF=NULL, RANG=15, NIVEAU=1, ID_PERE=NULL
WHERE ID='MENUDYN002';