create or replace view RESERVATIONSANSDIFFUSION as
SELECT
    r."ID",r."IDMERE",r."QTE",r."DATY",r."IDPRODUIT",r."LIBELLEPRODUIT",r."CATEGORIEPRODUIT",r."PU",r."MONTANT",r."TVA",r."MONTANTTVA",r."MONTANTTTC",r."CATEGORIEPRODUITLIB",r."HEURE",r."DUREE",r."REMISE",r."IDBCFILLE",r."MONTANTREMISE",r."MONTANTFINAL",
    a.ID as IDDIFFUSION,
    a.ETAT,
    a.HEURE as HEUREDIFFUSION,
    a.DUREE as DUREEDIFFUSION,
    a.ETATLIB,
    a.idmedialib,
    rmere.IDSUPPORT,
    s.VAL AS IDSUPPORTLIB,
    rmere.ETAT as ETATMERE,
    r.REMARQUE,
    r.SOURCE
FROM RESERVATIONDETAILS_LIB r
         LEFT JOIN ACTE_LIB a ON a.IDRESERVATIONFILLE = r.ID
         LEFT JOIN RESERVATION rmere ON rmere.ID = r.IDMERE
         LEFT JOIN SUPPORT s ON s.ID = rmere.IDSUPPORT
WHERE a.id IS NULL AND RMERE.etat >=11;


INSERT INTO EMISSION (ID, NOM, TARIFPLATEAU, TARIFPARAINAGE, SECONDEPARAINAGE, DUREE, IDSUPPORT, IDGENRE) VALUES
      ('EMIS104','BA+PUB',0,0,0,900,'SUPP002','TEM000002');

INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','06:00','06:15',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','08:15','08:18',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','08:40','08:43',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','10:00','10:03',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','12:00','12:02',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','12:15','12:17',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','12:45','12:47',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','12:53','12:57',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','13:15','13:17',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','13:43','13:45',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','16:33','16:35',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','17:15','17:20',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','17:55','18:00',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','19:20','19:25',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','19:40','19:42',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','19:47','19:57',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','20:40','20:50',NULL,NULL);

INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','06:00','06:15',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','08:15','08:18',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','08:40','08:43',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','10:00','10:03',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','12:00','12:02',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','12:15','12:17',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','12:45','12:47',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','12:53','12:57',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','13:15','13:17',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','13:43','13:45',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','16:33','16:35',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','17:15','17:20',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','17:55','18:00',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','19:20','19:25',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','19:40','19:42',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','19:47','19:57',NULL,NULL);
INSERT INTO EMISSIONDETAILS (ID, IDMERE, JOUR, HEUREDEBUT, HEUREFIN, HEUREDEBUTCOUPURE, HEUREFINCOUPURE)
VALUES ('EDETS'||SEQEMISSIONDETAILS.nextval,'EMIS104','Lundi','20:40','20:50',NULL,NULL);
