INSERT INTO USERMENU (ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES ('USRMEN0121',NULL,'MNDN0018040012','diffuseur',NULL,NULL,1);
INSERT INTO USERMENU (ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES ('USRMEN0122',NULL,'MNDN0018040012','front',NULL,NULL,1);
INSERT INTO USERMENU (ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES ('USRMEN0123',NULL,'MNDN0018040012','caisse',NULL,NULL,1);
INSERT INTO USERMENU (ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES ('USRMEN0124',NULL,'MNDN0018040013','diffuseur',NULL,NULL,1);
INSERT INTO USERMENU (ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES ('USRMEN0125',NULL,'MNDN0018040013','front',NULL,NULL,1);
INSERT INTO USERMENU (ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES ('USRMEN0126',NULL,'MNDN0018040013','caisse',NULL,NULL,1);


INSERT INTO MENUDYNAMIQUE (ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES ('MNDN0000002','Mon profil','fa fa-edit','module.jsp?but=utilisateur/utilisateur-modif.jsp&refuser=<%=u.getUser().getRefuser()%>',3,3,'MNDN0018040011');
