CREATE OR REPLACE VIEW "AS_INGREDIENTS_LIB" ("ID", "LIBELLE", "SEUIL", "UNITE", "QUANTITEPARPACK", "PU", "ACTIF", "PHOTO", "CALORIE", "DURRE", "COMPOSE", "IDCATEGORIEINGREDIENT", "CATEGORIEINGREDIENT", "IDCATEGORIE", "IDFOURNISSEUR", "DATY", "BIENOUSERV", "ETATLIB", "COMPTE_VENTE", "COMPTE_ACHAT", "PV", "TVA", "IDSUPPORT", "IDPOINT") AS 
 SELECT
	ing.id,
	ing.LIBELLE,
	ing.SEUIL,
	au.VAL AS unite,
	ing.QUANTITEPARPACK,
	ing.pu,
	ing.ACTIF,
	ing.PHOTO,
	ing.CALORIE,
	ing.DURRE,
	ing.COMPOSE,
	cating.id AS IDCATEGORIEINGREDIENT ,
	catIng.VAL AS CATEGORIEINGREDIENT,
	ing.CATEGORIEINGREDIENT AS idcategorie,
	ing.idfournisseur,
	ing.daty,
	catIng.desce AS bienOuServ,
	CASE
		WHEN ing.id IN (
		SELECT
			idproduit
		FROM
			INDISPONIBILITE i ) THEN 'INDISPONIBLE'
		WHEN ing.id NOT IN (
		SELECT
			idproduit
		FROM
			INDISPONIBILITE i ) THEN 'DISPONIBLE'
	END AS etatlib,
	ing.COMPTE_VENTE,
	ing.COMPTE_ACHAT,
	ing.pv,
	ing.tva,
	ing.IDSUPPORT,
	sup.IDPOINT
FROM
	as_ingredients ing
LEFT JOIN AS_UNITE AU ON
	ing.UNITE = AU.ID
LEFT JOIN CATEGORIEINGREDIENTLIB catIng ON
	catIng.id = ing.CATEGORIEINGREDIENT
LEFT JOIN SUPPORT sup ON
	sup.id = ing.IDSUPPORT ;