CREATE OR REPLACE VIEW RESERVATIONAVECDIFFUSION AS
SELECT
    r."ID",r."IDMERE",r."QTE",r."DATY",r."IDPRODUIT",r."LIBELLEPRODUIT",r."CATEGORIEPRODUIT",r."PU",r."MONTANT",r."TVA",r."MONTANTTVA",r."MONTANTTTC",r."CATEGORIEPRODUITLIB",r."HEURE",r."DUREE",r."REMISE",r."IDBCFILLE",r."MONTANTREMISE",r."MONTANTFINAL",
    a.ID as IDDIFFUSION,
    a.ETAT,
    a.HEURE as HEUREDIFFUSION,
    a.DUREE as DUREEDIFFUSION,
    a.ETATLIB,
    a.idmedialib,
    rmere.IDSUPPORT,
    s.VAL AS IDSUPPORTLIB,
    rmere.ETAT as ETATMERE,
    rmere.REMARQUE as campagne,
    r.remarque
FROM RESERVATIONDETAILS_LIB r
    LEFT JOIN ACTE_LIB a ON a.IDRESERVATIONFILLE = r.ID
    LEFT JOIN RESERVATION rmere ON rmere.ID = r.IDMERE
    LEFT JOIN SUPPORT s ON s.ID = rmere.IDSUPPORT
WHERE a.ID IS NOT NULL;


CREATE OR REPLACE VIEW RESERVATIONSDETAILS_CREE AS
SELECT
    r."ID",r."IDMERE",r."QTE",r."DATY",r."IDPRODUIT",r."LIBELLEPRODUIT",r."CATEGORIEPRODUIT",r."PU",r."MONTANT",r."TVA",r."MONTANTTVA",r."MONTANTTTC",r."CATEGORIEPRODUITLIB",r."HEURE",r."DUREE",r."REMISE",r."IDBCFILLE",r."MONTANTREMISE",r."MONTANTFINAL",
    a.ID as IDDIFFUSION,
    a.ETAT,
    a.HEURE as HEUREDIFFUSION,
    a.DUREE as DUREEDIFFUSION,
    a.ETATLIB,
    a.idmedialib,
    rmere.IDSUPPORT,
    s.VAL AS IDSUPPORTLIB,
    rmere.ETAT as ETATMERE,
    rmere.REMARQUE as campagne,
    r.remarque
FROM RESERVATIONDETAILS_LIB r
    LEFT JOIN ACTE_LIB a ON a.IDRESERVATIONFILLE = r.ID
    LEFT JOIN RESERVATION rmere ON rmere.ID = r.IDMERE
    LEFT JOIN SUPPORT s ON s.ID = rmere.IDSUPPORT
WHERE rmere.ETAT = 1;

CREATE OR REPLACE VIEW RESERVATIONSDETAILS_VALIDE AS
SELECT
    r."ID",r."IDMERE",r."QTE",r."DATY",r."IDPRODUIT",r."LIBELLEPRODUIT",r."CATEGORIEPRODUIT",r."PU",r."MONTANT",r."TVA",r."MONTANTTVA",r."MONTANTTTC",r."CATEGORIEPRODUITLIB",r."HEURE",r."DUREE",r."REMISE",r."IDBCFILLE",r."MONTANTREMISE",r."MONTANTFINAL",
    a.ID as IDDIFFUSION,
    a.ETAT,
    a.HEURE as HEUREDIFFUSION,
    a.DUREE as DUREEDIFFUSION,
    a.ETATLIB,
    a.idmedialib,
    rmere.IDSUPPORT,
    s.VAL AS IDSUPPORTLIB,
    rmere.ETAT as ETATMERE,
    rmere.REMARQUE as campagne,
    r.remarque
FROM RESERVATIONDETAILS_LIB r
    LEFT JOIN ACTE_LIB a ON a.IDRESERVATIONFILLE = r.ID
    LEFT JOIN RESERVATION rmere ON rmere.ID = r.IDMERE
    LEFT JOIN SUPPORT s ON s.ID = rmere.IDSUPPORT
WHERE rmere.ETAT = 11;


CREATE OR REPLACE VIEW RESERVATIONSDETAILS_ANNULE AS
SELECT
    r."ID",r."IDMERE",r."QTE",r."DATY",r."IDPRODUIT",r."LIBELLEPRODUIT",r."CATEGORIEPRODUIT",r."PU",r."MONTANT",r."TVA",r."MONTANTTVA",r."MONTANTTTC",r."CATEGORIEPRODUITLIB",r."HEURE",r."DUREE",r."REMISE",r."IDBCFILLE",r."MONTANTREMISE",r."MONTANTFINAL",
    a.ID as IDDIFFUSION,
    a.ETAT,
    a.HEURE as HEUREDIFFUSION,
    a.DUREE as DUREEDIFFUSION,
    a.ETATLIB,
    a.idmedialib,
    rmere.IDSUPPORT,
    s.VAL AS IDSUPPORTLIB,
    rmere.ETAT as ETATMERE,
    rmere.REMARQUE as campagne,
    r.remarque
FROM RESERVATIONDETAILS_LIB r
    LEFT JOIN ACTE_LIB a ON a.IDRESERVATIONFILLE = r.ID
    LEFT JOIN RESERVATION rmere ON rmere.ID = r.IDMERE
    LEFT JOIN SUPPORT s ON s.ID = rmere.IDSUPPORT
WHERE rmere.ETAT = 0;


CREATE OR REPLACE VIEW RESERVATIONSDETAILS_TOUS AS
SELECT
    r."ID",r."IDMERE",r."QTE",r."DATY",r."IDPRODUIT",r."LIBELLEPRODUIT",r."CATEGORIEPRODUIT",r."PU",r."MONTANT",r."TVA",r."MONTANTTVA",r."MONTANTTTC",r."CATEGORIEPRODUITLIB",r."HEURE",r."DUREE",r."REMISE",r."IDBCFILLE",r."MONTANTREMISE",r."MONTANTFINAL",
    a.ID as IDDIFFUSION,
    a.ETAT,
    a.HEURE as HEUREDIFFUSION,
    a.DUREE as DUREEDIFFUSION,
    a.ETATLIB,
    a.idmedialib,
    rmere.IDSUPPORT,
    s.VAL AS IDSUPPORTLIB,
    rmere.ETAT as ETATMERE,
    rmere.REMARQUE as campagne,
    r.remarque
FROM RESERVATIONDETAILS_LIB r
    LEFT JOIN ACTE_LIB a ON a.IDRESERVATIONFILLE = r.ID
    LEFT JOIN RESERVATION rmere ON rmere.ID = r.IDMERE
    LEFT JOIN SUPPORT s ON s.ID = rmere.IDSUPPORT;
