ALTER TABLE BONDECOMMANDE_CLIENT
ADD echeance VARCHAR(500);
 
ALTER TABLE BONDECOMMANDE_CLIENT
ADD modereglement VARCHAR(500);
 
CREATE OR REPLACE FORCE VIEW "BC_CLIENT_FORM" ("ID", "DATY", "ETAT", "REMARQUE", "DESIGNATION", "MODEPAIEMENT", "IDCLIENT", "REFERENCE", "IDDEVISE", "IDMAGASIN", "DATEBESOIN", "IDSUPPORT","ECHEANCE","MODEREGLEMENT") AS 
  SELECT
    bc."ID",bc."DATY",bc."ETAT",bc."REMARQUE",bc."DESIGNATION",bc."MODEPAIEMENT",bc."IDCLIENT",bc."REFERENCE",bc."IDDEVISE",bc."IDMAGASIN",bc."DATEBESOIN",
    CAST('' as VARCHAR2(255)) as idSupport , bc.echeance,bc.modereglement
FROM BONDECOMMANDE_CLIENT bc;

ALTER TABLE BONDECOMMANDE_CLIENT_FILLE
ADD reference VARCHAR(500);
 
CREATE OR REPLACE FORCE VIEW "INSERTIONBCFILLE" ("ID", "PRODUIT", "IDBC", "QUANTITE", "PU", "MONTANT", "TVA", "REMISE", "IDDEVISE", "UNITE", "REMARQUE", "UNITEREMISE","REFERENCE") AS 
  SELECT p."ID",p."PRODUIT",p."IDBC",p."QUANTITE",p."PU",p."MONTANT",p."TVA",p."REMISE",p."IDDEVISE",p."UNITE",p."REMARQUE",
       '' AS uniteRemise , p.reference
FROM BONDECOMMANDE_CLIENT_FILLE p;

CREATE OR REPLACE FORCE VIEW "BC_CLIENT_FILLE_CPL_LIB2" ("ID", "PRODUIT", "IDBC", "QUANTITE", "PU", "MONTANT", "TVA", "REMISE", "IDDEVISE", "UNITE", "PRODUITLIB", "COMPTE", "REMARQUE", "MONTANTHT", "MONTANTTVA", "MONTANTTTC","REFERENCE") AS 
  SELECT
    bcf.ID,
    bcf.PRODUIT,
    bcf.IDBC,
    bcf.QUANTITE,
    bcf.PU,
    bcf.MONTANT,
    bcf.TVA,
    bcf.REMISE,
    bcf.IDDEVISE,
    bcf.UNITE,
    i.LIBELLE AS PRODUITlib,
    i.COMPTE_VENTE AS Compte,
    bcf.REMARQUE,
    bcf.PU*bcf.QUANTITE as MontantHt,
    (bcf.PU*bcf.QUANTITE)*(bcf.TVA/100) as MontantTva,
    ((bcf.PU*bcf.QUANTITE)*(bcf.TVA/100))+((bcf.PU*bcf.QUANTITE)) as MontantTtc,
    bcf.reference
FROM
    bondecommande_client_fille bcf
        JOIN as_ingredients i ON
        i.id = bcf.PRODUIT;



CREATE OR REPLACE FORCE VIEW "BONDECOMMANDE_CLIENT_CPL" ("ID", "DATY", "ETAT", "REMARQUE", "DESIGNATION", "MODEPAIEMENT", "MODEPAIEMENTLIB", "IDCLIENT", "IDCLIENTLIB", "REFERENCE", "IDMAGASINLIB", "ECHEANCE", "MODEREGLEMENT", "ETATLIB") AS 
  SELECT
bc.ID,
bc.DATY,
bc.ETAT,
bc.REMARQUE,
bc.DESIGNATION,
bc.MODEPAIEMENT,
m.VAL AS MODEPAIEMENTLIB,
bc.IDCLIENT,
c.NOM AS IDCLIENTLIB,
bc.REFERENCE,
m2.VAL AS IDMAGASINLIB,
bc.echeance,
bc.modereglement,
CASE
    WHEN bc.ETAT = 0 THEN '<span style=color: green;>ANNULEE</span>'
    WHEN bc.ETAT = 1 THEN '<span style=color: green;>CREE</span>'
    WHEN bc.ETAT = 11 THEN '<span style=color: green;>VALIDEE</span>'
END AS ETATLIB

FROM BONDECOMMANDE_CLIENT bc
LEFT JOIN CLIENT c ON c.id = bc.IDCLIENT
LEFT JOIN MODEPAIEMENT m ON m.id = bc.MODEPAIEMENT
LEFT JOIN MAGASIN m2 ON m2.id = bc.IDMAGASIN
;